bindsym $mod+Ctrl+b exec firefox
bindsym $mod+Ctrl+t exec Telegram
bindsym $mod+Ctrl+p exec 1password
bindsym $mod+Ctrl+k exec keepassxc
bindsym $mod+Ctrl+e exec pcmanfm-qt
bindsym $mod+Ctrl+l exec lens-desktop
bindsym $mod+Ctrl+o exec obsidian
bindsym $mod+Ctrl+s exec slack
bindsym $mod+Ctrl+r exec bruno

bindsym $mod+Ctrl+g exec /home/hani/.local/share/JetBrains/Toolbox/apps/goland/bin/goland
bindsym $mod+Ctrl+y exec /home/hani/.local/share/JetBrains/Toolbox/apps/pycharm/bin/pycharm

bindsym $mod+Ctrl+w exec /home/hani/bin/wireguard-toggle.sh
bindsym $mod+Ctrl+c exec /home/hani/bin/kubectl-ctx-switcher.sh

bindsym $mod+Shift+x exec $locking
bindsym $mod+Shift+z exec systemctl sleep
